alias gs='git status'
alias gd='git diff'
alias gfp='git fetch --prune'
alias gpr='git pull --rebase'
alias gco='git checkout'
alias gpron='git config --global pull.rebase true'
alias gproff='git config --global pull.rebase false'
alias gconf='git config --global -l'